### ISSUE TITLE
Play with the API

### ISSUE THREAD

**Issue by ScottWheelNett** [ScottWheelNett/django-journey#25]
created from read and implement django tutorial pg 2 #21

**Comment by ScottWheelNett** [comment]
>>> import django
>>> django.setup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting LOGGING_CONFIG, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by ScottWheelNett** [comment]
I'll just do python manage.py shell, which works fine

**Comment by ScottWheelNett** [comment]
[scott@scott-pc djangojourney]$ python manage.py shell
<~><< Have A Spiffy Day! >><~>
Python 3.6.3 (default, Oct 24 2017, 14:48:20) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from polls.models import Question, Choice
>>> Question.objects.all()
<QuerySet []>
>>> Choice.objects.all()
<QuerySet []>
>>> from django.utils import timezone
>>> timezone.now()
datetime.datetime(2018, 1, 11, 18, 45, 34, 372656, tzinfo=<UTC>)
>>> q = Question(question_text="What's up?", pub_date=timezone.now())
>>> Question.objects.all()
<QuerySet []>
>>> q
<Question: Question object (None)>
>>> q.save()
>>> Question.objects.all()
<QuerySet [<Question: Question object (1)>]>
>>> Question.objects.get()
<Question: Question object (1)>
>>> q.id
1
>>> q.question_text
"What's up?"
>>> q.pub_date
datetime.datetime(2018, 1, 11, 18, 46, 39, 488186, tzinfo=<UTC>)
>>> q.question_text = "What is up!?"
>>> q.save()
>>> Question.objects.all()
<QuerySet [<Question: Question object (1)>]>
>>> Question.objects.all()[0]
<Question: Question object (1)>
>>> Question.objects.all()[0].question_text
'What is up!?'
>>>

**Comment by ScottWheelNett** [comment]
added __str__ methods to Question and Choice
added was_published_recently to Question

**Comment by ScottWheelNett** [comment]
restart console without applying migrations

**Comment by ScottWheelNett** [comment]
>>> from polls.models import Question, Choice
>>> Question.objects.all()
<QuerySet [<Question: What is up!?>]>
>>> Question.objects.filter(pk=1)
<QuerySet [<Question: What is up!?>]>
>>> Question.objects.filter(pk=2)
<QuerySet []>
>>> Question.objects.filter(id=1)
<QuerySet [<Question: What is up!?>]>
>>> Question.objects.filter(question_text__startswith="What")
<QuerySet [<Question: What is up!?>]>
>>> from django.utils import timezone
>>> current_year = timezone.now().year
>>> Question.objects.filter(pub_date__year=current_year)
<QuerySet [<Question: What is up!?>]>
>>> Question.objects.get(id=2)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
polls.models.DoesNotExist: Question matching query does not exist.
>>> Question.objects.get(pk=1)
<Question: What is up!?>
>>> q=Question.objects.get(pk=1)
>>> q.was_published_recently()
True
>>> q.choice_set
<django.db.models.fields.related_descriptors.create_reverse_many_to_one_manager.<locals>.RelatedManager object at 0x7f775eca6a20>
>>> q.choice_set.all()
<QuerySet []>
>>> q.choice_set.create(choice_text="Not Much..", votes=0)
<Choice: Not Much..>
>>> q.choice_set.create(choice_text="The sky...", votes=0)
<Choice: The sky...>
>>> c = q.choice_set.create(choice_text="just hacking again..", votes=0)
>>> c
<Choice: just hacking again..>
>>> c.question
<Question: What is up!?>
>>> c.question.choice_set.all()
<QuerySet [<Choice: Not Much..>, <Choice: The sky...>, <Choice: just hacking again..>]>
>>> c.question.choice_set.count()
3
>>> Choice.objects.filter(question__pub_date__year=current_year)
<QuerySet [<Choice: Not Much..>, <Choice: The sky...>, <Choice: just hacking again..>]>
>>> c = Choice.objects.filter(choice_text__startswith="just hacking")
>>> c
<QuerySet [<Choice: just hacking again..>]>
>>> c.delete()
(1, {'polls.Choice': 1})

**Comment by ScottWheelNett** [comment]
Shouldn't I migrate the changes to the database..?

**Comment by ScottWheelNett** [comment]
[scott@scott-pc djangojourney]$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, polls, sessions
Running migrations:
  No migrations to apply.

**Comment by ScottWheelNett** [comment]
but I changed the models... maybe only when I create new model classes or change the fields. All I did was create the string methods and another method.
So no migrations after adding methods, I guess

**Comment by ScottWheelNett** [comment]
committing changes.. closing issue
